DROP TABLE IF EXISTS review_likes CASCADE;
DROP TABLE IF EXISTS review CASCADE;
DROP TABLE IF EXISTS film_director CASCADE;
DROP TABLE IF EXISTS director CASCADE;
DROP TABLE IF EXISTS film_genre CASCADE;
DROP TABLE IF EXISTS likes CASCADE;
DROP TABLE IF EXISTS friends CASCADE;
DROP TABLE IF EXISTS film CASCADE;
DROP TABLE IF EXISTS mpa CASCADE;
DROP TABLE IF EXISTS genres CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;
DROP TABLE IF EXISTS events CASCADE;

CREATE TABLE IF NOT EXISTS "user"
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(255),
    birthday TIMESTAMP,
    email    VARCHAR(255),
    login    VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS genres
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS mpa
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS film
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255),
    description VARCHAR(1000),
    releaseDate TIMESTAMP,
    duration    INTEGER,
    mpa_id      INTEGER REFERENCES mpa (id)
);

CREATE TABLE IF NOT EXISTS friends
(
    user_id   INTEGER NOT NULL,
    friend_id INTEGER NOT NULL,
    constraint "user_friend_user_id_user_id_fk"
        foreign key (user_id) references "user" (id) ON UPDATE CASCADE ON DELETE CASCADE,
    constraint "user_friend_friend_id_user_id_fk"
        foreign key (friend_id) references "user" (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS likes
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER,
    film_id INTEGER,
    constraint "user_like_user_id_user_id_fk"
        foreign key (user_id) references "user" (id) ON UPDATE CASCADE ON DELETE CASCADE,
    constraint "user_like_film_id_film_id_fk"
        foreign key (film_id) references film (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS film_genre
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id  INTEGER,
    genre_id INTEGER,
    constraint "film_genre_film_id_film_id_fk"
        foreign key (film_id) references film (id) ON UPDATE CASCADE ON DELETE CASCADE,
    constraint "film_genre_genre_id_genre_id_fk"
        foreign key (genre_id) references genres (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS director
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS film_director
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id     INTEGER,
    director_id INTEGER,
    constraint "film_director_film_id_film_id_fk"
        foreign key (film_id) references film (id) ON UPDATE CASCADE ON DELETE CASCADE,
    constraint "film_director_director_id_director_id_fk"
        foreign key (director_id) references director (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS review
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content     VARCHAR(1000),
    useful      INTEGER DEFAULT 0,
    is_positive BOOLEAN,
    film_id     INTEGER,
    user_id     INTEGER,
    CONSTRAINT "review_film_id_film_id_fk"
        FOREIGN KEY (film_id) REFERENCES film (id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT "review_user_id_user_id_fk"
        FOREIGN KEY (user_id) REFERENCES "user" (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS review_likes
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_positive BOOLEAN,
    user_id     INTEGER,
    review_id   INTEGER,
    CONSTRAINT "review_like_user_id_user_id_fk"
        FOREIGN KEY (user_id) REFERENCES "user" (id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT "review_like_review_id_review_id_fk"
        FOREIGN KEY (review_id) REFERENCES review (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS events
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    event_type INTEGER                             NOT NULL, -- одно из значениий LIKE, REVIEW или FRIEND
    operation  INTEGER                             NOT NULL, -- одно из значениий REMOVE, ADD, UPDATE
    entity_id  INTEGER                             NOT NULL  -- идентификатор сущности, с которой произошло событие

);

CREATE TRIGGER IF NOT EXISTS like_insert_event_log
    AFTER INSERT
    ON likes
    FOR EACH ROW
CALL "ru.yandex.practicum.filmorate.storage.trigger.LikesTrigger";

CREATE TRIGGER IF NOT EXISTS friends_insert_event_log
    AFTER INSERT
    ON friends
    FOR EACH ROW
CALL "ru.yandex.practicum.filmorate.storage.trigger.FriendsTrigger";

CREATE TRIGGER IF NOT EXISTS review_insert_event_log
    AFTER INSERT
    ON review
    FOR EACH ROW
CALL "ru.yandex.practicum.filmorate.storage.trigger.ReviewTrigger";

CREATE TRIGGER IF NOT EXISTS like_update_event_log
    AFTER UPDATE
    ON likes
    FOR EACH ROW
CALL "ru.yandex.practicum.filmorate.storage.trigger.LikesTrigger";

CREATE TRIGGER IF NOT EXISTS friends_update_event_log
    AFTER UPDATE
    ON friends
    FOR EACH ROW
CALL "ru.yandex.practicum.filmorate.storage.trigger.FriendsTrigger";

CREATE TRIGGER IF NOT EXISTS review_update_event_log
    AFTER UPDATE
    ON review
    FOR EACH ROW
CALL "ru.yandex.practicum.filmorate.storage.trigger.ReviewTrigger";

CREATE TRIGGER IF NOT EXISTS like_delete_event_log
    AFTER DELETE
    ON likes
    FOR EACH ROW
CALL "ru.yandex.practicum.filmorate.storage.trigger.LikesTrigger";

CREATE TRIGGER IF NOT EXISTS friends_delete_event_log
    AFTER DELETE
    ON friends
    FOR EACH ROW
CALL "ru.yandex.practicum.filmorate.storage.trigger.FriendsTrigger";

CREATE TRIGGER IF NOT EXISTS review_delete_event_log
    AFTER DELETE
    ON review
    FOR EACH ROW
CALL "ru.yandex.practicum.filmorate.storage.trigger.ReviewTrigger";