
CREATE TABLE IF NOT EXISTS "user" (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    birthday TIMESTAMP,
    email VARCHAR(255),
    login VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS genres (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS mpa (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS film (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    description VARCHAR(1000),
    releaseDate TIMESTAMP,
    duration INTEGER,
    mpa_id INTEGER REFERENCES mpa(id)
);

CREATE TABLE IF NOT EXISTS friends (
    user_id INTEGER NOT NULL,
    friend_id INTEGER NOT NULL,
    constraint "user_friend_user_id_user_id_fk"
    foreign key (user_id) references "user" (id) ON DELETE CASCADE,
    constraint "user_friend_friend_id_user_id_fk"
    foreign key (friend_id) references "user" (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS likes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER,
    film_id INTEGER,
    constraint "user_like_user_id_user_id_fk"
    foreign key (user_id) references "user" (id) ON DELETE CASCADE,
    constraint "user_like_film_id_film_id_fk"
    foreign key (film_id) references film (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS film_genre (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id INTEGER,
    genre_id INTEGER,
    constraint "film_genre_film_id_film_id_fk"
    foreign key (film_id) references film (id) ON DELETE CASCADE,
    constraint "film_genre_genre_id_genre_id_fk"
    foreign key (genre_id) references genres (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS director (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS film_director (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id INTEGER,
    director_id INTEGER,
    constraint "film_director_film_id_film_id_fk"
    foreign key (film_id) references film (id) ON DELETE CASCADE,
    constraint "film_director_director_id_director_id_fk"
    foreign key (director_id) references director (id) ON DELETE CASCADE
);







